name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWt0UGN6QnpJaXdpVWtWUVR5STZJbmR2Y210bGNpMXlaWEFpTENKVVIxOUJVRWxmU1VRaU9pSXhOalUwTmpJM01DSXNJbFJIWDBGUVNWOUlRVk5JSWpvaU1XVXhaV1l4WW1KaU5tVTRZelppWXprd01ESXdOMk5oTldFeE1XTm1ObUlpTENKVVIxOUNUMVJmVkU5TFJVNGlPaUl5TURBNE5qVTJOamd4T2tGQlIxZEZObVpsTTNOVmJrNUtSamhEVkZVeWRrbHVjRmxIYkZReGNrTlJTamN3SWl3aVJrbE1SU0k2TXpVeExDSkdTVXhGWDA1QlRVVWlPaUpiVXpBeExUQTRYU0JRYjNOemFXSnNlU0JCYkdOb1pXMXBjM1FnV3pFd09EQndYU0JiUkhWaGJGMGdRRUZ1YVcxbGMxOVBZMlZoYmk1dGEzWWlMQ0pKUkNJNklsQnZjMTh3WVRrNFlUMHlQVEV3T0RCd0lpd2lRMDFFSWpvaVdtMWFkR05IVm01SlF6RndTVWgwY0dKc09XMWhWM2hzWmxOQmRGcHRiSE5rUjFaNVdESk9kbUpZUW5OYVdHZG5TVzFTZVZsWVpEQmFXR2d3VUZkYWRtSnVVbTFoVjNoc1VGZG5kV1JJVW0xUGJsSnNaVWhST1VwNVFrSmliV3gwV2xoTloxUXlUbXhaVnpSblNucHdiV0l5TlRCWk1qbHpZak5KT1dReWFIQmtSMVUyV20wNWRXUklUbkJsYlZVNVRYcFpObVZFTUhoTlJIQTFVRlJGZDA5dFZuVlpWMHB6V2xRd2JsbHRWakJrTWxac1ltbG9NRXhFUVhOT1ZFRjNTMU5qTmxsWGVIZGhSMFU1U2pKc2JVdEhlREJMU0ZGelRrUnJOVXRUZDNoTVIyeHRTMGQ0TUV0SVVYTk9WRUYzUzFOM2IwMVRNRzlrUXpBd1QxUnJjRXRUT0hoTVJFRndTMU5qYVVsRE1YUlpXRUZuVFVOQmRHSlhWakJaVjFKb1pFZEZObU42Y0doSlNGSndaRWQ0YkZCVFNrRlJWelZ3WWxkV2VsZ3dPV3BhVjBaMVNXbEJkR0pYVmpCWlYxSm9aRWRGTm1ONmNIcEpTRkp3WkVkNGJGQlRTa0ZSVnpWd1lsZFdlbGd3T1dwYVYwWjFTV2xCZEdKWFZqQlpWMUpvWkVkRloyUkhiREJpUjFVNVNXdENRbUp0YkhSYVdFNW1WREpPYkZsWE5HbEpRekZxVDI1WloySkhiR2xqTTFvd1dWaFplRWxETVhkamJWWjZXbGhSWjA1cFFYUmFlVUY1VGtSQloweFlUV2ROVkd0NVRVaG5lRTFFWjNkSlF6RjVTVVJOZDBsRE1YZGhXR2htV20weE1FbEliREZrYWxGNVRVaEJaMHhZVGpKa1IwWXlUVk14ZDFsWVNtaGlXRTFuWkVoV2RWcFVNSGhQYlZwd1lrY3dkRm96U21oaFZ6UTVUVU5CZEZrelNtMUpSRkV3U1VNeGMySXlaSE5hV0Zwc1lrTkNiR051U25aamFVRjBXWHB3YUVsSGVIQlpiVGwzWkZoTloweFhSbXBKUkVsblRGZEdhVWxFVVhkaGVVRjBXWHB3ZWtsSFRuWmpTR3RuWlRJNWQxZ3lXbkJpUjFZNVNVTXhOU0lzSWxSSVZVMUNUa0ZKVENJNklqRTJNQ0lzSWtGVlZFaFBVaUk2SWpZMk56STNOVEl4TnpjaWZRPT0=
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
